services:
  db:
    image: postgres:16-alpine # Use the official PostgreSQL 16 Alpine image
    container_name: task-manager-postgres # A friendly name for the container
    environment:
      POSTGRES_DB: taskmanagerdb      # Name of the database to create
      POSTGRES_USER: user             # Username for the database
      POSTGRES_PASSWORD: mysecretpassword # Password for the user
    ports:
      - "5432:5432" # Map host port 5432 to container port 5432
    volumes:
      - db_data:/var/lib/postgresql/data # Persist data in a named volume

volumes:
  db_data: # Define the named volume